user_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('users.urls'), name='user_app')
]

# Adding media as a url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views
from .views import CustomPasswordResetView

app_name = 'user_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('user/list/a/', views.UserListView.as_view(), name='list'),
    path('user/create/a/', views.UserCreateView.as_view(), name='create'),
    path('user/update/<int:pk>/a/', views.UserUpdateView.as_view(), name='update'),
    path('user/delete/<int:pk>/a/', views.UserDeleteView.as_view(), name='delete'),
    path('user/register/c/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('user/profile/<int:pk>/c/', views.UserProfile.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(next_page='user_app:home'), name='logout'),

        path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

templates/partials/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <!-- <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2023</span> -->
    </div>
</footer>

templates/partials/navbar.html
{% load static %}

<nav class="navbar p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
        <a class="navbar-brand brand-logo-mini" href="index.html"><img alt="logo" src="{% static 'assets/images/logo-mini.svg' %}"/></a>
    </div>
    <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" data-toggle="minimize" type="button">
            <span class="mdi mdi-menu"></span>
        </button>
        <ul class="navbar-nav w-100">
            <li class="nav-item w-100">
                <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                    <input class="form-control" placeholder="Search products" type="text">
                </form>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-settings d-none d-lg-block">
                <a class="nav-link" href="{% url 'user_app:home' %}">
                    <i class="mdi mdi-home text-warning"></i>
                </a>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block border-left">
                <a class="nav-link" href="{% url 'user_app:profile' user.id %}">
                    <i class="mdi mdi-account text-primary"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#" id="profileDropdown">
                    <div class="navbar-profile">
                        <img alt="" class="img-xs rounded-circle" src="{{ user.profile.image.url }}">
                        <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ user.username | capfirst }}</p>
                        <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                </a>
                <div aria-labelledby="profileDropdown" class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list">
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="{% url 'user_app:profile' user.id %}">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-account text-success"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject mb-1">Profile</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-logout text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject mb-1">Log out</p>
                        </div>
                    </a>
                    <form id="logout-form" action="{% url 'user_app:logout' %}" method="POST" style="display: none;">
                        {% csrf_token %}
                    </form>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" data-toggle="offcanvas" type="button">
            <span class="mdi mdi-format-line-spacing"></span>
        </button>
    </div>
</nav>

templates/partials/sidebar.html
{% load static %}

<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo" href="{% url 'user_app:home' %}"> Employeee</a>
        <a class="sidebar-brand brand-logo-mini" href="{% url 'user_app:home' %}"><img alt="logo" src="{% static 'assets/images/logo-mini.svg' %}"/></a>
    </div>
    <ul class="nav">
        <li class="nav-item profile">
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        <img alt="" class="img-xs rounded-circle " src="{{ user.profile.image.url }}">
                        <span class="count bg-success"></span>
                    </div>
                    <div class="profile-name">
                        <h5 class="mb-0 font-weight-normal">{{ user.username | capfirst }}</h5>
                        <span>{{ user.user_type }}</span>
                    </div>
                </div>
                <a data-toggle="dropdown" href="#" id="profile-dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div aria-labelledby="profile-dropdown" class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list">
                    <a class="dropdown-item preview-item" href="#">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-account text-primary"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Profile</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                </div>
            </div>
        </li>
        <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'user_app:home' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a aria-controls="ui-basic" aria-expanded="false" class="nav-link" data-toggle="collapse" href="#ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-account"></i>
              </span>
                <span class="menu-title">Users</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{% url 'user_app:list' %}">View Users</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'user_app:create' %}">Add Users</a></li>
                </ul>
            </div>
        </li>
    </ul>
</nav>