user_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('users.urls'), name='user_app')
]

# Adding media as a url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views
from .views import CustomPasswordResetView

app_name = 'user_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('user/list/a/', views.UserListView.as_view(), name='list'),
    path('user/create/a/', views.UserCreateView.as_view(), name='create'),
    path('user/update/<int:pk>/a/', views.UserUpdateView.as_view(), name='update'),
    path('user/delete/<int:pk>/a/', views.UserDeleteView.as_view(), name='delete'),
    path('user/register/c/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('user/profile/<int:pk>/c/', views.UserProfile.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(next_page='user_app:home'), name='logout'),

        path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
from io import BytesIO
from django.contrib.auth.models import AbstractUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from PIL import Image
import sys

class MyUser(AbstractUser):
    """ User Model with Abstract User"""
    city = models.CharField(max_length=255)
    user_type = models.CharField(max_length=255, choices=(('admin', 'Admin'), ('customer', 'Customer')))

    def __str__(self):
        return self.username

class Profile(models.Model):
    """ Profile Model with Profile Image"""
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    image = models.ImageField(default='default.webp', upload_to='images/profile/', null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def save(self, *args, **kwargs):
        if self.image and self.image.size > 1000000:
            img = Image.open(self.image)
            output = BytesIO()
            img.save(output, format='JPEG', quality=70)
            output.seek(0)
            self.image = InMemoryUploadedFile(output, 'ImageField', f"{self.image.name.split('.')[0]}.jpg", 'image/jpeg', sys.getsizeof(self.image), None)
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from users.models import MyUser, Profile
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives



class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email address',
            'type': 'email',
            'name': 'email',
            'autocomplete': 'email',
        })
    )
    
    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
        subject = render_to_string(subject_template_name, context)
        subject = ''.join(subject.splitlines())
        body = render_to_string(email_template_name, context)
        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name:
            html_email = render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')
        email_message.send()

    def save(self, domain_override=None,
             subject_template_name='users/password_reset_subject.txt',
             email_template_name='users/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
        """
        Generate a one-use only link for resetting password and send it to the user.
        """
        email = self.cleaned_data["email"]
        email_field_name = MyUser.get_email_field_name()
        for user in self.get_users(email):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                'email': email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name, email_template_name, context, from_email,
                user.email, html_email_template_name=html_email_template_name,
            )


class UserCreateForm(forms.ModelForm):
    """ User Create or Registration Form """
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'password', 'city', 'user_type')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'user_type': forms.Select(attrs={'class': 'form-control'}),
        }

class UserUpdateForm(forms.ModelForm):
    """ User Update Form by Admin """
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'city', 'user_type')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'user_type': forms.Select(attrs={'class': 'form-control'}),
        }

class CustomerUpdateForm(forms.ModelForm):
    """ User Profile Detail Update Form"""
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'username', 'email', 'city',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CustomerProfileForm(forms.ModelForm):
    """ User profile photo form """
    class Meta:
        model = Profile
        fields = ('image',)
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from users.models import MyUser
from users.forms import UserCreateForm, UserUpdateForm, CustomerUpdateForm, CustomerProfileForm, CustomPasswordResetForm
from django.contrib.auth.views import PasswordResetView, LogoutView

from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _




class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'  # Template for password reset confirmation
    success_url = reverse_lazy('login')  # Redirect URL after successful password reset
    form_class = SetPasswordForm  # Form class for setting a new password
    post_reset_login = False  # Disable automatic login after password reset

    def form_valid(self, form):
        # Hash the password before saving
        form.save()
        return super().form_valid(form)



class CustomLogoutView(LogoutView):
    def get_next_page(self):
        return reverse_lazy('user_app:home') 

class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = reverse_lazy('user_app:password_reset_done')
    template_name = 'users/password_reset.html'

class MyMixin(LoginRequiredMixin, UserPassesTestMixin):
    """ Mixin for Authentication and User is Admin or not """
    def test_func(self):
        return self.request.user.user_type == 'admin'

@login_required()
def home(request):
    """ Home Page """
    admin_count = MyUser.objects.filter(user_type='admin').count()
    customer_count = MyUser.objects.filter(user_type='customer').count()
    context = {
        'a_count': admin_count,
        'c_count': customer_count,
    }
    return render(request, 'users/home.html', context)

class UserRegistrationView(CreateView):
    """ New User Registration """
    model = MyUser
    form_class = UserCreateForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('user_app:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        password = form.cleaned_data['password']
        user.set_password(password)
        messages.success(self.request, f"{user.username} is created successfully!")
        user.save()
        return redirect(reverse_lazy('user_app:home'))

class UserListView(MyMixin, ListView):
    """ List of Users for Admin """
    model = MyUser
    template_name = 'users/list.html'
    context_object_name = 'data'

class UserCreateView(MyMixin, CreateView):
    """ Create a new User by Admin """
    model = MyUser
    form_class = UserCreateForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        user = form.save(commit=False)
        password = form.cleaned_data['password']
        user.set_password(password)
        messages.success(self.request, f"{user.username} is created successfully!")
        user.save()
        return redirect(reverse_lazy('user_app:list'))

class UserUpdateView(MyMixin, UpdateView):
    """ Update a user by Admin """
    model = MyUser
    form_class = UserUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        super(UserUpdateView, self).form_valid(form)
        messages.success(self.request, f"user is updated successfully!")
        return redirect(reverse_lazy('user_app:list'))

class UserDeleteView(MyMixin, DeleteView):
    """ Delete a user by Admin """
    model = MyUser
    template_name = 'users/delete.html'
    success_url = reverse_lazy('user_app:list')

    def form_valid(self, form):
        super(UserDeleteView, self).form_valid(form)
        messages.warning(self.request, f"user is deleted successfully!")
        return redirect(reverse_lazy('user_app:list'))

class UserProfile(LoginRequiredMixin, UpdateView):
    """ All User Profile Page """
    def get(self, request, **kwargs):
        user = request.user
        data = MyUser.objects.get(id=user.id)
        c_form = CustomerUpdateForm(instance=user)
        p_form = CustomerProfileForm(instance=user.profile)

        context = {
            'data': data,
            'c_form': c_form,
            'p_form': p_form,
        }
        return render(request, 'users/profile.html', context)

    def post(self, request, *args, **kwargs):
        user = request.user
        c_form = CustomerUpdateForm(request.POST, instance=user)
        p_form = CustomerProfileForm(request.POST, request.FILES, instance=user.profile)
        if c_form.is_valid() and p_form.is_valid():
            username = c_form.cleaned_data['username']
            c_form.save()
            p_form.save()
            messages.success(request, f"{username}'s profile has been updated successfully!")
        return redirect(reverse_lazy('user_app:profile', kwargs={'pk': user.id}))

templates/users/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-10">
          <h2 class="card-title">User's List</h2>
        </div>
        <div class="col-md-2">
          <a href="{% url 'user_app:create' %}" class="btn btn-primary">Add New User</a>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Username</th>
              <th>Email</th>
              <th>City</th>
              <th>User Type</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          {% for user in data %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ user.first_name }} {{ user.last_name }}</td>
              <td>{{ user.username }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.city }}</td>
              <td>{{ user.user_type }}</td>
              <td>
                <a href="{% url 'user_app:update' user.id %}" class="btn btn-primary mx-1">Edit</a>
                <a href="{% url 'user_app:delete' user.id %}" class="btn btn-danger mx-1">Delete</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/users/login.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Login</h3>
                            <hr>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.username | as_crispy_field }}
                                </div>
                                <div class="form-group">
                                    {{ form.password | as_crispy_field }}
                                </div>
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-block enter-btn">Login</button>
                                </div>
                                <hr>
                                <p class="sign-up">Don't have an Account?<a href="{% url 'user_app:register' %}"> Sign Up</a></p>
                                <p class="forgot-password text-right">Forgot Password? <a href="{% url 'user_app:password_reset' %}">Forgot Password?</a></p>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/logout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}"/>

    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}"/>

    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />

    <!-- Favicon Icon -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />

  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="row w-100 m-0">
          <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
            <div class="card col-lg-6 mx-auto">
              <div class="card-body ">
                <div class="text-center my-5">
                  <h1>You have been logged out.</h1>
                  <hr>
                  <h6>
                    Wants to Login Again?<a href="{% url 'user_app:login' %}" class="ml-2">Click Here</a>
                  </h6>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
        </div>
        <!-- row ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>

  </body>
</html>

templates/users/password_reset.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Reset my password</h3>
                            <hr>
                            <form method="post" action="{% url 'user_app:password_reset' %}">
                                {% csrf_token %}
                                {{ form.as_p }}
                           
                           
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-block enter-btn">Reset my password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/password_reset_complete.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Password Reset Complete</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    <div class="card col-lg-4 mx-auto">
                        <div class="card-body px-5 py-5">
                            <h3 class="card-title text-left mb-3">Password Reset Complete</h3>

                            <p>Your password has been set. You can now <a href="{% url 'user_app:login' %}">log in</a> with your new password.</p>
                                
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>

    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
</body>
</html>

templates/users/password_reset_email.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Email</title>
</head>
<body>
    <p>{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}</p>
    
    <p>{% blocktrans %}Please go to the following page and choose a new password:{% endblocktrans %}</p>
    
    <p><a href="{{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}">{{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}</a></p>
    
    <p>{% blocktrans %}Your username, in case you've forgotten: {{ user.get_username }}{% endblocktrans %}</p>
    
    <p>{% blocktrans %}Thanks for using our site!{% endblocktrans %}</p>
    
    <p>{% blocktrans %}The {{ site_name }} team{% endblocktrans %}</p>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title>User Management</title>

    <!-- plugins:css -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" rel="stylesheet">

    <link href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}" rel="stylesheet">

    <!-- Layout styles -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- End layout styles -->
    <link href="{% static 'assets/images/favicon.png' %}" rel="shortcut icon"/>

</head>
<body>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="row w-100 m-0">
            <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                <div class="card col-lg-6 mx-auto">
                    <div class="card-body px-3 py-3">
                        <h2 class="card-title text-left m-3">Registration</h2>
                        <hr>
                        <form method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>First Name *</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Last Name *</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>UserName *</label>
                                        {{ form.username }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email *</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Password *</label>
                                        {{ form.password }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>City *</label>
                                        {{ form.city }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>User Type *</label>
                                {{ form.user_type }}
                            </div>
                            <hr>
                            <div class=" text-center">
                                <button class="btn btn-primary btn-block enter-btn" type="submit">Register</button>
                            </div>
                            <hr>
                            <p class="sign-up">Exsting User? <a href="{% url 'user_app:login' %}"> Login</a></p>
                        </form>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- row ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->

<!-- plugins:js -->
<script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>


<!-- inject:js -->
<script src="{% static 'assets/js/off-canvas.js' %}"></script>
<script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'assets/js/misc.js' %}"></script>
<script src="{% static 'assets/js/settings.js' %}"></script>
<script src="{% static 'assets/js/todolist.js' %}"></script>

</body>
</html>